# Apresentação:

Na construção de modelos de **redes neurais**, uma das áreas matemáticas mais utilizadas é a **Álgebra Linear**. O objetivo desse código é justamente estudar a Álgebra Linear pela ótica da computação, recriando os cálculos de forma manual na busca por entende-los melhor. O objetivo aqui não é ficar teorizando muito sobre os elementos matemáticos. Vou diretamente ao ponto da utilização computacional dos conhecimentos da **álgebra linear**.

## Livros Textos:

Aqui, eu vou trabalhar com uma gama de livros que abordam o tema, são eles:

* [Deep Learning (Good Fellow)](https://www.deeplearningbook.org/)
* [The Matrix Cookbook](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf)
* [Algebra Linear e suas Aplicações (Anton Torres)](https://brogdomonzao.wordpress.com/wp-content/uploads/2011/10/c3a1lgebra_linear_e_aplicac3a7c3b5es_-_howard_anton_portuguc3aas.pdf)

## Bibliotecas Python:

Farei uso de algumas biblotecas para validar resultados e explorar capacidades computacionalmente mais otimizadas, mas o objetivo aqui é fazer tudo na mão. Algumas bibliotecas utilizadas aqui são:

* [Numpy](https://numpy.org/doc/stable/index.html)



In [16]:
# Bibliotecas:
import numpy as np
from time import time # Para verificar tempo de operação
from random import randint as rand # Para gerar números aleatórios

# Soma de Matrizes:

In [17]:
def checamQuadrada(m):
  '''
  Função para verificar se uma detemrinada
  matriz é quadrada.

  # Entrada:
  list: matriz a ser verificada.

  # Saída:
  bool: True se a matriz for quadrada;
  False se a matriz não for quadrada.
  '''
  # Hipotese, matriz é quadrada:
  q = True

  # Verificando hipotese
  for i,_ in enumerate(m):
    if len(m) != len(m[i]):
      q = False # Mudando resposta

  return q

In [18]:
def somamat(v1,v2):
  '''
  Função construida para aplicar a soma de matrizes
  de matrizes:

  # Entradas:
  list: Primeira Matriz;
  list: Segunda Matriz.

  # Saídas:
  list: Resultado da soma
  '''

  # Chegando definição da soma de matriz:
  if not checamQuadrada(v1) and checamQuadrada(v2):
    print('Soma de Matriz não definida')
    return

  # Instanciando Matriz de Elementos resultados:
  C = [[0 for _ in range(len(v1))] for _ in range(len(v2))]

  for i in range(len(C)):
    for j in range(len(C[i])):
      C[i][j] = v1[i][j] + v2[i][j]

  return C

In [19]:
A = [[2,2],[2,2]]
B = [[3,3],[3,3],[3,3,3],[2,1,6]]

In [20]:
C = [[0 for _ in range(len(A))] for _ in range(len(B))]

In [21]:
len(B)

4

In [22]:
checamQuadrada(A)

True

# Produto Interno:

O Produto de Matrizes está definido quando,

$$ \textbf{C}_{(m \times p)} = \textbf{A}_{(m \times n)} \textbf{B}_{(n \times p)}$$

de modo que podemos modemos formula-lo matematicamente como sendo,

$$\textbf{C}_{i,j} = \sum_{k}\textbf{A}_{i,k}\textbf{B}_{k,j}$$

In [23]:
# Função de Produto Interno:
def dotprod(v1,v2):
  '''
  Função construida para aplicar o produto interno
  de matrizes de forma manual.

  # Entradas:
  numpy.matrix: Primeira Matriz;
  numpy.matrix: Segunda Matriz.

  # Saídas:
  numpy.matrix: Resultado do Produto Interno. (Se de certo);
  NoneType: Se o produto de matrizes não estiver definido.
  '''
  # Elementos da Matriz:
  m = v1.shape[0] # Qtd de linhas da primeira Matriz
  n = v1.shape[1] # Qtd de colunas da primeira Matriz
  p = v2.shape[1] # Qtd de colunas da segunda Matriz.

  # Verificando se o produto interno está bem definido:
  if v1.shape[1] != v2.shape[0]:
      print('Produto de Matriz não definido!')
      return None

  # Criando Matriz Vazia:
  C = [[0 for _ in range(B.shape[1])] for _ in range(A.shape[0])]

  # Realizando o produto Interno:
  for i in range(m):
    for j in range(p):
      for k in range(n):
        C[i][j] += A[i,k] * B[k,j]

  return np.matrix(C)

In [24]:
# Matrizes de Exemplo:
A = np.matrix([[1,2], [3,4]])
B = np.matrix([[5,6], [7,8]])

In [25]:
# Produto Interno:
dprod_func = dotprod(A,B)
dprod_nump = np.dot(A,B)

# Validando resultado
dprod_func == dprod_nump

matrix([[ True,  True],
        [ True,  True]])

In [26]:
dprod_func

matrix([[19, 22],
        [43, 50]])

# Produto de Hadamard (element-wise):

O **produto de Hadamard** é um produto interno especial, uma **operação binária**, que realiza o produto interno apenas entre as entradas de mesmo indice de modo que,

$$\text{A}\odot{\text{B}}_{ij}=\text{A}_{ij}\text{B}_{ij}$$

Para implementamos, podemos utilizar a mesma função criada para o **produto interno** tradicional e acrescentar uma validação lógica.

In [27]:
def HadamardProd(v1, v2):
    '''
    Função construída para aplicar o produto de Hadamard (elemento a elemento)
    de matrizes de forma manual.

    # Entradas:
    numpy.ndarray: Primeira Matriz;
    numpy.ndarray: Segunda Matriz.

    # Saídas:
    numpy.ndarray: Resultado do Produto de Hadamard (se bem definido);
    NoneType: Se o produto de Hadamard não estiver definido.
    '''
    # Verificando se o produto de Hadamard está bem definido:
    if v1.shape != v2.shape:
        print('Produto de Hadamard não definido! As matrizes devem ter a mesma dimensão.')
        return None

    # Criando a matriz de saída com o mesmo shape
    C = np.zeros(v1.shape)

    # Realizando o produto de Hadamard:
    for i in range(v1.shape[0]):
        for j in range(v1.shape[1]):
            C[i, j] = v1[i, j] * v2[i, j]

    return C

In [28]:
hProd_func = HadamardProd(A,B)
hProd_nump = np.multiply(A,B)

# Validando resultado
hProd_func == hProd_nump

matrix([[ True,  True],
        [ True,  True]])

# Determinantes

In [ ]:
def detcof(A):
  '''
    Calcula a determinante de uma matriz,
  dado os seus cofatores.

  # Entrada:
  numpy.ndarray: Matriz quadrada.

  # Saída:
  float: Determinante da Matriz.
  '''

  for i in

In [29]:
A

matrix([[1, 2],
        [3, 4]])

In [36]:
C = [[1,2,3],[4,5,6]]

In [51]:
diagPrincipal = 1
diagSecundaria = 1
for i in range(len(A)):
  for j in range(len(A[i])):
    if i == j:
      print(i,j)
      diagPrincipal *= A[i,j]
      print(A[i,j])

0 0
1


In [41]:
abs(-1)

1